on:
  workflow_dispatch:

concurrency:
  group: register-command
  cancel-in-progress: true

jobs:
  register-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Register Command
        run: >
          DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
          DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_GUILD_ID=${{ secrets.DISCORD_GUILD_ID }}
          node tools/register.js
